### PR TITLE
Fix wrapping issues with typing animation

### LINKED ISSUE #59: Extra linebreaks during typing animation for headings
## Information

- URL: https://hacktoberfest.com/
- Browser: Firefox Developer Edition 131.0b1 (aarch64)
- Operating System: macOS Sonoma 14.5
- Device: MacBook Pro 16" 2021 (M1)

### Description

At certain resolutions (observed at 1920x1080), the typing animation used on headings will sometimes result in an extra linebreak being rendered during the animation that disappears once the animation completes.

### Steps to reproduce

At 1920x1080, load the homepage.

https://github.com/user-attachments/assets/97989ff3-50c3-4706-83a4-d749cecaacdf

https://github.com/user-attachments/assets/6ef07b22-30e7-4891-a6be-80e90f40d29f

### Expected behavior

Animation does not interfere with how the heading text would naturally render.

### PR DESCRIPTION
**Pull request by Thunder-Blaze**
## What should this PR do?

- Made the cursor disappear as soon as the typing is done by setting idle timer to 1 ms
- Made the cursor's position to absolute so that it doesn't interfere with the natural rendering of text

Minor issue: when looked carefully the line height of the cursor doesn't matches with that of the heading, but it is not really noticable until seen carefully

https://github.com/user-attachments/assets/7b210812-dc79-4432-ba77-9bc756f4b4df

## What issue does this relate to?

Closes #59

## What are the acceptance criteria?

Cursor no longer causes wrapping issues as reported in the issue.

### CODE REVIEW

File: src/components/type.js [hunk 1]
```diff
@@ -2,7 +2,7 @@ import { useEffect, useMemo, useRef, useState } from 'react';
 import styled from 'styled-components';
 
 const interval = 100;
-const idle = 1000;
+const idle = 1;
```
Comment (MattIPv4) [inline src/components/type.js:5]: I don't think we need to change this, this is an intentional design decision to leave the cursor visible for a second

File: src/components/type.js [hunk 2]
```diff
@@ -2,7 +2,7 @@ import { useEffect, useMemo, useRef, useState } from 'react';
...
 
 const srOnly = {
```
Comment (MattIPv4) [inline src/components/type.js:7]: Can we use a styled component for this?

File: src/components/type.js [hunk 3]
```diff
@@ -13,6 +13,15 @@ const srOnly = {
   clip: 'rect(0, 0, 0, 0)',
 };
 
+const cursorStyle = {
```
Comment (MattIPv4) [inline src/components/type.js:16]: Can we use a styled component for this?

File: src/components/type.js (hunk 1 above)
Comment (Thunder-Blaze) [reply src/components/type.js]: Oh I thought so, since the name was idle. I reverted the change to idle, tried to use the styled components, I think it should work fine now

File: src/components/type.js (hunk 2 above)
Comment (MattIPv4) [reply src/components/type.js]: Can we make the screen-reader text a styled component too, while we're here, please?

**Review by MattIPv4 — CHANGES_REQUESTED** [review]
This looks great in Chromium-based browsers, but in Firefox this doesn't seem to work at all:

https://github.com/user-attachments/assets/b5fa6b20-abbb-43ac-9bb7-b8819f5e849a

It's also broken in a similar way on Safari now too:

https://github.com/user-attachments/assets/6d6ec5bf-6774-4fba-a554-a5f1f280b757

File: src/components/type.js (hunk 2 above)
Comment (Thunder-Blaze) [reply src/components/type.js]: done, and sorry I forgot to check cross-browser compatibility
I also fixed the issue the best I could
I have tested it on chromium and firefox

**Review by MattIPv4 — APPROVED** [review]
This appears to work on Chrome/Firefox/Safari, thank you very much!
